name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v2
      
    - name: Log in to the Container registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag url-toolbox:$(date +%s)
    - name: Build and push
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/benni0/url-toolbox:latest
          ghcr.io/benni0/ioc-toolbox:latest
